apiVersion: v1
kind: Secret
metadata:
  name: ssd-db-secret
  namespace: project-ns
stringData:
  # Spring Boot가 자동으로 인식하는 Key로 변경
  SPRING_DATASOURCE_URL: "jdbc:mysql://ssd-db-svc/ssd_db?serverTimezone=UTC"
  SPRING_DATASOURCE_USERNAME: "ssd-user"
  SPRING_DATASOURCE_PASSWORD: "test123" # ◀◀ (주의) JSP 예제와 암호가 다릅니다.
---
apiVersion: v1
kind: Secret
metadata:
  name: hdd-db-secret
  namespace: project-ns
stringData:
  # Spring Boot가 자동으로 인식하는 Key로 변경
  SPRING_DATASOURCE_URL: "jdbc:mysql://hdd-db-svc/hdd_db?serverTimezone=UTC"
  SPRING_DATASOURCE_USERNAME: "hdd-user"
  SPRING_DATASOURCE_PASSWORD: "test123"
