apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ssd-was-hpa
  namespace: project-ns
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ssd-was-dep
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 25 # 25% 조건
