apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssd-web-dep
  namespace: project-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ssd-web
  template:
    metadata:
      labels:
        app: ssd-web
    spec:
      # --- SSD 노드 배치 조건 ---
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: disktype
                operator: In
                values: ["ssd"]
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config-vol
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
      volumes:
      - name: nginx-config-vol
        configMap:
          name: ssd-web-cm
